## Principle Component Analysis (PCA)

Its an unsupervised machine learning problem<br>
Its an complex technique<br>
Underline Maths is too complex

Main goal is to reduce Curse of dimentionality

PCA tries to bring the higher dimention dataset to lower dimention<br>
The best thing about PCA is its takes the best possible lower dimention in consideration so that we can capture the essence of that higher dimention data into lower dimention <br>
So that when the ML model works on the lower dimention dataset the output will be good only

Benifits of using PCA
<br>
1. Faster execution of the Algorithm
2. Visualization

### Geometric Intuition

#### Feature Selection <br>
Selecting the imortant columns and removing the rest which will not help in prediction<br><br>

How this work mathametically<br>
Consider we have an scatter plot : here on there are multiple plots on the graph so ,the graph has an x axis and y axis  and on X axis there will me one of the columns and on Y there will be other <br>
So after plotting i will have to see that which one of the axis has the wider spread<br>
It means that consider X axis i will see the staring point and ending point on the X axis and measure its width <br>
Same way i will calculate the width of the starting point on the Y axis and its ending point <br>
Then we will compare both the width of X and width of Y Which is greater<br><br>
After comparing we will select that axis/column having more spread/width on graph<br><br>
This is how Feature Selection Works

#### Feature Extraction <br>

In some cases using Feature Selection does not work ,i.e we are not able to dicide which columns to consider and which to not.<br>
So in such case We use Feature Extraction<br><br>

Main idea is : we create an new columns which tells us about the number of columns we are about to merge into one <br><br>

In short this is what PCA does he forgots the existing features/columns and create a new set of featuers and from that new set of features PCA select the most important/best subset of features
<br><br>

How PCA is performed<br>
In the scatter graph , what PCA does is find new set of co-ordinate axis , it will rotate the axis in such a way that an new set of axis is formed<br>
So in this new set of Co-ordinate any one axis spread will change and then we can compre the width of the new co-ordinate axis and select the best feature/column <br><br>
When we rotate the original axis and get the new axis , we call the new axis as Principal Component 1 (PC1) and Principal Component 2 (PC2)<br>
After selecting the Principal component , we will transform that PC<br>
No.of Pc <= No.of original features

Every point in the scatter plot has an x axis and an y axis , we can consider points as vector which has 2 components, 1 in x direction and other in y direction,<br> 
so now we have to project this vector in any other vector , <br><br> so we have to find unit vector of the other vector , we represent unit vector as u <br>
so to find the point of the old vector on the new vector we use vector projection <br><br>
Formula to find vector projection is :  u*X/magnitude of u
<br><br> Since its unit vector so the magnitude of u will be 1 , so we can write the formula as<br><br>
formula : (u * x) or we can say (u transpose(u^t) * x)<br><br>
so the projection we will get after the formula will be an scalar value or we can say distance/length<br><br>

So what we have to do is maximize the Variance <br>
how we will calculate variance<br>

(1/n) Σ (xi-x')^2 

xi = u^t
x' = original data mean when pointer on the u it will become u^t*xmean or (u^tx')<br><br>

so now variance = (from i=1 to n)Σ ( u^txi - u^tx' )^2 / n <br><br>

Now using mathmetical we have to find such (u) for this the variance is maximum<br>
So we can say we will find the best u from all posibilities

## Co-variance and co-variance matrix <br>
Mean does not tell as how much the data is spread , so to solve this problem Variance came <br>
But variance has an problem too , the spread on both the axis on the graph can be difference , so variance does not show us the relationship between the two axis or feature.<br><br>

So here comes Co-variance, it shows the relation ship between both the axis <br>
formula = (x*y) for all points / no.of points
<br>
Its is closely related to co-relation<br>
only difference is we have range in co-relation of [-1,0,1] , in co-variance we dont have such thing<br><br>

So in short we can say that co-variance is used to find how axis behave regarding to each other / relationship of axis with each other.
<br><br><br>
Co-Variance Matrix<br>
Suppose we have 2D data,so it will be 2x2 matrix like
$$
\begin{bmatrix} cov(x1,x1) & cov(x1,x2) \\ cov(x2,x1) & cov(x2,x2) \end{bmatrix}
$$   

cov = Co-Variance <br>
cov(x1,x1) is var(x1) same for cov(x2,x2)<br>
cov(a,b) = cov(b,a)<br>
So its an square matrix ans Symmetric too<br>
Diagonal of this matrix are var(x) and other elements are cov(x,y)<br>
Adv of Cov  = It shows the spread of all the axis as it has variance of all the axis<br>
and other it will show the relationship of all the axis , its negative or positive<br><br>

#### Linear Transformation ,Eigen Vector and Eigen Values

How does Matrices work as Linear Transformation <br>
When we apply Matrices transformation , all the vector in the co-ordinate system , the direction and magnitude changes , basically they are getting thrown of their span (axis)<br>

So we can say that matrics are linear transformation which when applied to co-ordinate system then the vector in the co-ordinate system changes the magnitude and span.

What are Eigen vector<br>
They are special vector ,which when transformation is applied ,there is not changes in them<br>
So when we applie Linear transformatino we get atleast 2 eigen vector,which have same direction only difference can be magnitude/scale<br>

A * V = lambda V<br>
where A = matrix<br>
V = eigen vector<br>
lambda = eigen value<br>
Its means that when we apply linear transforation on this vector then its as if that we are multiplying the vector with any scale/value<br>
This realtionship is always true for eigen vector

What are Eigen Values<br>
Eigen vector streach or shrink , the value by which they strach ot shrink is called Eigen values

Why we use Eigen vector and Eigen value in PCA<br><br>
the highest Eigen vector tell us the highest unit variance and that has the  highest variance

### Step by Step Solution of PCA

we have an dataset with 3 columne F1,F2,F3 <br>
so in scatter plot its in 3D space and we have to bring it in lower dimention <br><br>

Step 1. Mean Center the data (Find the mean and minus with all data points)<br>
Step 2. Find co-variance matrix
<br>
Step 3. Find the Eigen value and Eigen vector for the co-variance matrix 
<br>highest Eigen vector value then PC1 and so on.
<br>So its upon us to either merge PC1 and PC2 and go in 2D or only select PC1 and do it in 1D.

### Coding Example

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(23)
mu_vec = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])

class_sample = np.random.multivariate_normal(mu_vec,cov_mat1,20)

df = pd.DataFrame(class_sample,columns=['F1','F2','F3'])
df['target'] = 1

mu_vec2 = np.array([0,0,0])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])

class_sample2 = np.random.multivariate_normal(mu_vec2,cov_mat2,20)

df2 = pd.DataFrame(class_sample2,columns=['F1','F2','F3'])
df2['target'] = 0

df = pd.concat((df,df2),ignore_index=True)
df = df.sample(40)

In [4]:
df.head()

          F1        F2        F3  target
2  -0.367548 -1.137460 -1.322148       1
34 -0.822939 -1.598109  0.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [5]:
import plotly.express as px

fig = px.scatter_3d(
    df,
    x=df['F1'],
    y=df['F2'],
    z=df['F3'],
    color=df['target'].astype(str)
)

fig.update_traces(
    marker=dict(
        size=12,
        line=dict(
            width=2,
            color='DarkSlateGrey'
        )
    )
)

fig.show()

In [6]:
# step 1 Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [7]:
#step 2 finding Co-variance matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
covariance_matrix

array([[ 1.02564103,  0.06781177, -0.12497686],
       [ 0.06781177,  1.02564103, -0.15241116],
       [-0.12497686, -0.15241116,  1.02564103]])

In [8]:
# step 3 finding eigne value and eigne vector
eigne_values,eigne_vector = np.linalg.eig(covariance_matrix)
eigne_values,eigne_vector

(array([1.25911792+0.j, 0.95953081+0.j, 0.85827434+0.j]),
 array([[-0.51038783+0.j, -0.78846385+0.j,  0.34326234+0.j],
        [-0.569092  +0.j,  0.60894401+0.j,  0.55255904+0.j],
        [ 0.64470037+0.j, -0.08667156+0.j,  0.75950607+0.j]]))

In [9]:
pc = eigne_vector[0:2]
pc

array([[-0.51038783+0.j, -0.78846385+0.j,  0.34326234+0.j],
       [-0.569092  +0.j,  0.60894401+0.j,  0.55255904+0.j]])

In [10]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

                  PC1                 PC2  target
0  0.560815+0.000000j -1.471948+0.000000j       1
1  1.740278+0.000000j -0.643400+0.000000j       0
2 -0.706342+0.000000j -0.080489+0.000000j       1
3 -0.786474+0.000000j -1.876564+0.000000j       1
4  1.105696+0.000000j  1.622028+0.000000j       1

In [11]:
new_df['PC1'] = new_df['PC1'].apply(lambda x: x.real)
new_df['PC2'] = new_df['PC2'].apply(lambda x: x.real)

In [12]:
import plotly.express as px
new_df['target'] = new_df['target'].astype(str)

fig = px.scatter(
    x=new_df['PC1'],
    y=new_df['PC2'],
    color=new_df['target'].astype(str)
)

fig.update_traces(
    marker=dict(
        size=12,
        line=dict(
            width=2,
            color='DarkSlateGrey'
        )
    )
)

fig.show()

### Praticl example on MNIST Dataset

In [34]:
df = pd.read_csv("train_image.csv")
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
X = df.iloc[:,1:]
Y = df.iloc[:,0]

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [20]:
X_train.shape

(33600, 784)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [22]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [23]:
import time 
start = time.time()
y_pred = knn.predict(X_test)
print(time.time() - start)

19.413744926452637

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9648809523809524

#### Now we will do the PCA and repeat the same model algorithm

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [38]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
#PCA 
from sklearn.decomposition import PCA
pca = PCA(n_components=100) # how many best columns we need

In [40]:
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [42]:
X_train_trf.shape

(33600, 100)

In [43]:
knn = KNeighborsClassifier()
knn.fit(X_train_trf,y_train)

KNeighborsClassifier()

In [44]:
y_pred = knn.predict(X_test_trf)

z:\PYTHON\Python-RealLife-Problems\venv\Lib\site-packages\joblib\externals\loky\backend\context.py:150: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "z:\PYTHON\Python-RealLife-Problems\venv\Lib\site-packages\joblib\externals\loky\backend\context.py", line 227, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\rajpr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rajpr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rajpr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [45]:
accuracy_score(y_test,y_pred)

0.9544047619047619

So we will noe change the component size and find the best component size or we can say u

In [ ]:
for i in range(1,785):
    pca = PCA(n_components=i)
    X_train_trf = pca.fit_transform(X_train)
    X_test_trf = pca.transform(X_test)
    knn = KNeighborsClassifier()
    knn.fit(X_train_trf,y_train)
    y_pred = knn.predict(X_test_trf)
    print(accuracy_score(y_test,y_pred))

0.2580952380952381
0.3236904761904762
0.5104761904761905
0.6663095238095238
0.7378571428571429
0.8227380952380953
0.8436904761904762
0.8721428571428571
0.886547619047619
0.9055952380952381
0.9116666666666666
0.9184523809523809
0.9276190476190476
0.9351190476190476
0.9384523809523809
0.9379761904761905
0.9407142857142857
0.94
0.9425
0.9442857142857143
0.9438095238095238
0.9441666666666667
0.9442857142857143
0.9457142857142857
0.9484523809523809
0.9479761904761905
0.9478571428571428
0.9471428571428572
0.949047619047619
0.9491666666666667
0.9507142857142857
0.9513095238095238
0.95
0.9504761904761905
0.950952380952381
0.9519047619047619
0.9517857142857142
0.9527380952380953
0.9533333333333334
0.9528571428571428
0.9522619047619048
0.9522619047619048
0.9523809523809523
0.9533333333333334
0.9528571428571428
0.9530952380952381
0.9530952380952381
0.9533333333333334
0.9527380952380953
0.9533333333333334
0.9545238095238096
0.954047619047619
0.9541666666666667
0.9541666666666667
0.9546428571428571
0.954047619047619
0.9548809523809524
0.9535714285714286
0.9538095238095238
0.9545238095238096
0.9547619047619048
0.9546428571428571
0.9551190476190476
0.9546428571428571
0.9545238095238096
0.9545238095238096
0.9536904761904762
0.9542857142857143
0.9544047619047619
0.9539285714285715
0.9547619047619048
0.9547619047619048
0.9552380952380952
0.955
0.955
0.9547619047619048
0.9546428571428571
0.9547619047619048
0.955
0.9552380952380952
0.9551190476190476
0.9546428571428571
0.9548809523809524
0.9545238095238096
0.9557142857142857
0.9557142857142857
0.9553571428571429
0.9553571428571429
0.955
0.955
0.9551190476190476
0.9547619047619048
0.9545238095238096
0.9546428571428571
0.9548809523809524
0.9545238095238096
0.9544047619047619
0.9544047619047619
0.9542857142857143
0.9544047619047619
0.9542857142857143
0.9541666666666667
0.9539285714285715
0.9539285714285715
0.9538095238095238
0.9536904761904762
0.9541666666666667
0.9536904761904762
0.9536904761904762
0.9530952380952381
0.9530952380952381
0.9534523809523809
0.9535714285714286
0.9533333333333334
0.9530952380952381
0.9528571428571428
0.9529761904761904
0.9533333333333334
0.9536904761904762
0.9536904761904762
0.9533333333333334
0.9529761904761904
0.9527380952380953
0.9528571428571428
0.9532142857142857
0.9534523809523809
0.9529761904761904
0.9529761904761904
0.9529761904761904
0.9528571428571428
0.9526190476190476
0.9529761904761904
0.9534523809523809
0.9535714285714286
0.9532142857142857
0.9534523809523809
0.9530952380952381
0.9530952380952381
0.9530952380952381
0.9533333333333334
0.9522619047619048
0.9516666666666667
0.9521428571428572
0.9514285714285714
0.9516666666666667
0.9520238095238095
0.9515476190476191
0.9516666666666667
0.9516666666666667
0.9520238095238095
0.9515476190476191
0.9517857142857142
0.9514285714285714
0.9521428571428572
0.9519047619047619
0.9516666666666667
0.9516666666666667
0.9516666666666667
0.9517857142857142
0.9519047619047619
0.9521428571428572
0.9515476190476191
0.9515476190476191
0.9517857142857142
0.9513095238095238
0.9511904761904761
0.9513095238095238
0.9514285714285714
0.950952380952381
0.9511904761904761
0.9515476190476191
0.950952380952381
0.9508333333333333
0.9508333333333333
0.9508333333333333
0.9508333333333333
0.9510714285714286
0.950952380952381
0.9513095238095238
0.9510714285714286
0.9513095238095238
0.9515476190476191
0.9511904761904761
0.9513095238095238
0.950595238095238
0.9511904761904761
0.9511904761904761
0.9516666666666667
0.9513095238095238
0.9511904761904761
0.9513095238095238
0.9513095238095238
0.9510714285714286
0.950952380952381
0.9511904761904761
0.9508333333333333
0.9507142857142857
0.950595238095238
0.9504761904761905
0.9507142857142857
0.950595238095238
0.950595238095238
0.9504761904761905
0.950595238095238
0.9502380952380952
0.9504761904761905
0.9504761904761905
0.9497619047619048
0.9502380952380952
0.9501190476190476
0.9495238095238095
0.9494047619047619
0.9489285714285715
0.949047619047619
0.9489285714285715
0.949047619047619
0.9489285714285715
0.949047619047619
0.9491666666666667
0.949047619047619
0.9494047619047619
0.949047619047619
0.9494047619047619
0.9495238095238095
0.9491666666666667
0.9491666666666667
0.9484523809523809
0.9485714285714286
0.9489285714285715
0.9495238095238095
0.9491666666666667
0.9489285714285715
0.9488095238095238
0.9485714285714286
0.9480952380952381
0.9485714285714286
0.9479761904761905
0.9482142857142857
0.9484523809523809
0.9486904761904762
0.9486904761904762
0.9484523809523809
0.9485714285714286
0.9484523809523809
0.9485714285714286
0.9482142857142857
0.9486904761904762
0.9483333333333334
0.9482142857142857
0.9485714285714286
0.9485714285714286
0.9482142857142857
0.9479761904761905
0.9479761904761905
0.9477380952380953
0.9477380952380953
0.9471428571428572
0.9472619047619047
0.9472619047619047
0.9471428571428572
0.9477380952380953
0.9478571428571428
0.9476190476190476
0.9476190476190476
0.9477380952380953
0.9472619047619047
0.9471428571428572
0.9472619047619047
0.9476190476190476
0.9471428571428572
0.9470238095238095
0.9470238095238095
0.9473809523809524
0.9476190476190476
0.9475
0.9473809523809524
0.9472619047619047
0.9471428571428572
0.9466666666666667
0.9471428571428572
0.9470238095238095
0.9471428571428572
0.9470238095238095
0.9471428571428572
0.9471428571428572
0.9469047619047619
0.9469047619047619
0.9471428571428572
0.9472619047619047
0.9472619047619047
0.9472619047619047
0.9472619047619047
0.9472619047619047
0.9471428571428572
0.9471428571428572
0.9472619047619047
0.9471428571428572
0.9471428571428572
0.9470238095238095
0.9467857142857142
0.9467857142857142
0.9470238095238095
0.9471428571428572
0.9466666666666667
0.9465476190476191
0.9467857142857142
0.9469047619047619
0.9467857142857142
0.9465476190476191
0.9464285714285714
0.9465476190476191
0.9460714285714286
0.9463095238095238
0.9460714285714286
0.9463095238095238
0.9457142857142857
0.9458333333333333
0.9461904761904761
0.945952380952381
0.945952380952381
0.9458333333333333
0.9460714285714286
0.945952380952381
0.9457142857142857
0.945952380952381
0.9460714285714286
0.9461904761904761
0.9464285714285714
0.945952380952381
0.945952380952381
0.9458333333333333
0.9458333333333333
0.945952380952381
0.945595238095238
0.9457142857142857
0.9454761904761905
0.9452380952380952
0.9451190476190476
0.945
0.9445238095238095
0.9447619047619048
0.9447619047619048
0.9448809523809524
0.9448809523809524
0.9451190476190476
0.9447619047619048
0.9448809523809524
0.945
0.9446428571428571
0.9446428571428571
0.9445238095238095
0.944047619047619
0.9439285714285715
0.9439285714285715
0.9441666666666667
0.944047619047619
0.9435714285714286
0.9434523809523809
0.9434523809523809
0.9434523809523809
0.9438095238095238
0.944047619047619
0.9439285714285715
0.9435714285714286
0.9435714285714286
0.9436904761904762
0.9436904761904762
0.9438095238095238
0.9439285714285715
0.9438095238095238
0.9438095238095238
0.9435714285714286
0.9438095238095238
0.9436904761904762
0.9433333333333334
0.9435714285714286
0.944047619047619
0.9438095238095238
0.9439285714285715
0.9438095238095238
0.9438095238095238
0.9438095238095238
0.9438095238095238
0.9438095238095238
0.9441666666666667
0.9441666666666667
0.9441666666666667
0.9441666666666667
0.9441666666666667
0.9439285714285715
0.9439285714285715
0.9436904761904762
0.9436904761904762
0.9438095238095238
0.9433333333333334
0.9434523809523809
0.9435714285714286
0.9436904761904762
0.9436904761904762
0.9436904761904762
0.9434523809523809
0.9434523809523809
0.9435714285714286
0.9433333333333334
0.9432142857142857
0.9430952380952381
0.9429761904761905
0.9429761904761905
0.9429761904761905
0.9429761904761905
0.9430952380952381
0.9429761904761905
0.9429761904761905
0.9429761904761905
0.9429761904761905
0.9433333333333334
0.9432142857142857
0.9428571428571428
0.9430952380952381
0.9430952380952381
0.9430952380952381
0.9430952380952381
0.9430952380952381
0.9430952380952381
0.9429761904761905
0.9428571428571428
0.9428571428571428
0.9426190476190476
0.9428571428571428
0.9428571428571428
0.9429761904761905
0.9428571428571428
0.9427380952380953
0.9428571428571428
0.9428571428571428
0.9427380952380953
0.9428571428571428
0.9429761904761905
0.9429761904761905
0.9429761904761905
0.9428571428571428
0.9428571428571428
0.9427380952380953
0.9426190476190476
0.9426190476190476
0.9426190476190476
0.9426190476190476
0.9426190476190476
0.9425
0.9422619047619047
0.9422619047619047
0.9422619047619047
0.9422619047619047
0.9422619047619047
0.9423809523809524
0.9423809523809524
0.9422619047619047
0.9422619047619047
0.9422619047619047
0.9422619047619047
0.9421428571428572
0.9421428571428572
0.9419047619047619
0.9421428571428572
0.9421428571428572
0.9419047619047619
0.9422619047619047
0.9422619047619047
0.9422619047619047
0.9421428571428572
0.9420238095238095
0.9419047619047619
0.9416666666666667
0.9416666666666667
0.9417857142857143
0.9417857142857143
0.9417857142857143
0.9416666666666667
0.9417857142857143
0.9419047619047619
0.9419047619047619
0.9419047619047619
0.9419047619047619
0.9419047619047619
0.9417857142857143
0.9415476190476191
0.9415476190476191
0.9414285714285714
0.9413095238095238
0.9411904761904762
0.9411904761904762
0.9413095238095238
0.9411904761904762
0.9411904761904762
0.9410714285714286
0.940952380952381
0.940952380952381
0.9410714285714286
0.9410714285714286
0.9410714285714286
0.9410714285714286
0.940952380952381
0.940952380952381
0.940952380952381
0.9410714285714286
0.9410714285714286
0.9411904761904762
0.9410714285714286
0.9410714285714286
0.940952380952381
0.9410714285714286
0.9410714285714286
0.9410714285714286
0.9408333333333333
0.9407142857142857
0.940952380952381
0.9408333333333333
0.9408333333333333
0.9408333333333333
0.940595238095238
0.9407142857142857
0.9404761904761905
0.9408333333333333
0.9408333333333333
0.9408333333333333
0.9407142857142857
0.9404761904761905
0.940595238095238
0.9407142857142857
0.940595238095238
0.9408333333333333
0.9407142857142857
0.9407142857142857
0.9403571428571429
0.9404761904761905
0.9404761904761905
0.9404761904761905
0.940595238095238
0.940595238095238
0.940595238095238
0.940595238095238
0.9403571428571429
0.9403571428571429
0.9403571428571429
0.9403571428571429
0.9403571428571429
0.9403571428571429
0.9403571428571429
0.9403571428571429
0.9404761904761905
0.9404761904761905
0.9404761904761905
0.9404761904761905