## MIssing values handled by<br>
Remove values<br>
Impute values <br>
    <t>1. Univarient <br> 2. Multivarient <br>

<br><br>
Univarient<br>
    1. Numeric <br> 2. Categorical

<br>
Numeric : mean ,median, random , end of distribution<br>
Categorical : mode ,missing 

<br><br>
Multivarient<br>
KNN imputer <br>
Iterative imputer mice

## Complete Case Analysis

Complete case analysis also called "list-wise deetion" of cases , consists in discarding observation where values in any of the variable are missing
<br>
CCA means literally analyzing onlt those observation for which there is information i all of the variable in the dataset

<br>
observation  = rows
variable  =  columns 
<br><br>
Assumption for CCA
<br>
1. Missing completely at random  : then remove that data if completely randomly then only

## Advantage
<br>
1.Easy to implement as no data manipulation required<br>
2.Prevent variable distributions

## Disadvantage
1.It can exclude a large fraction of the original dataset<br>
2.Excluded observation could be informative for the analysis <br>
3.When using our models in production , the model will not know how to handle missing data

## When to use CCA ?
1. missing completely at random<br>
2. Less than 5% missing data<br>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("data_science_job.csv")
df.head()

   enrollee_id      city  ...  training_hours target
0         8949  city_103  ...            36.0    1.0
1        29725   city_40  ...            47.0    0.0
2        11561   city_21  ...            83.0    0.0
3        33241  city_115  ...            52.0    1.0
4          666  city_162  ...             8.0    0.0

[5 rows x 13 columns]

In [5]:
df.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

In [6]:
df.shape

(19158, 13)

#### Mean and Median Imputation
<br>
If the distrubation is normal than use mean imputation <br>
If not then median

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [8]:
df_t = pd.read_csv('titanic_toy.csv')
df_t.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [9]:
df_t.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [10]:
X= df_t.drop(columns=['Survived'])
Y=df_t['Survived']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [13]:
X_train.shape,X_test.shape

((712, 3), (179, 3))

In [14]:
X_train.isnull().mean()

Age       0.196629
Fare      0.050562
Family    0.000000
dtype: float64

In [16]:
mean_age = X_train['Age'].mean()
median_age = X_train['Age'].median()

mean_fare = X_train['Fare'].mean()
median_fare = X_train['Fare'].median()

In [17]:
X_train['Age_median'] = X_train['Age'].fillna(median_age)
X_train['Age_mean'] = X_train['Age'].fillna(mean_age)

X_train['Fare_median'] =  X_train['Fare'].fillna(median_fare)
X_train['Fare_mean'] =  X_train['Fare'].fillna(mean_fare)

In [19]:
X_train.sample(4)

      Age     Fare  Family  Age_median   Age_mean  Fare_median  Fare_mean
703  25.0   7.7417       0        25.0  25.000000       7.7417     7.7417
740   NaN  30.0000       0        28.0  29.498846      30.0000    30.0000
504  16.0  86.5000       0        16.0  16.000000      86.5000    86.5000
460  48.0  26.5500       0        48.0  48.000000      26.5500    26.5500