### KNN imputer Working

Here the imputer calculate the Kth nearest neighour of the missing value form the column(feature) and fill the values with that values <br>
Main is the value of the K means how many neighbor to take into consideration while calculating the value for the missing row <br>
value of the neighbor and divide by the number of neighbor<br>

total of all the value of k / number of values

#### steps to follow

1. Find the Kth nearest neighbor (by finding the distance eudidean distance for this case)
2.  Find the values (har neighbor se uska value le ke mean nikal lena )

3. Distance formula sqrt (x2 - x2)^2 + (y2 - y1)^2 , for 2d coordinate system

We can have multiple missing values so we use other formula that is <br>
nan_eudidean distance = This handles the missing values in the data and calculate the distance<br>
Formula = dist(x,y) = sqrt(weight * sq .distance from present coordinate) , where weight = total No.of coordinates / No.of present coordinate (where all the values are present in both row in same column)

### Advantage(A) & Disadvantage(D)<br>
1. Its more accurate (A)
2. More number of calculation (D)
3. When deploy on server , we will have to upload the whole training set on serve (D)

In [40]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [41]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]
df.head(2)

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1

In [42]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [43]:
X = df.drop(columns=['Survived'])
Y= df['Survived']

In [44]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [45]:
X_train.head()

      Age  Pclass     Fare
331  45.5       1  28.5000
733  23.0       2  13.0000
382  32.0       3   7.9250
704  26.0       3   7.8542
813   6.0       3  31.2750

In [52]:
knn = KNNImputer()
#'distance','uniform' difference in uniform we add the values of the kth nearest neighbur and divide it by no.of neighbor (total of kth values)/no.of kth term

# but in distance = we will do the reciprocal of the values so
# (1/(distance of the value calculated) * value + 1/(other disatnce)* value) / 2

In [53]:
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [54]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

      Age  Pclass      Fare
0    45.5     1.0   28.5000
1    23.0     2.0   13.0000
2    32.0     3.0    7.9250
3    26.0     3.0    7.8542
4     6.0     3.0   31.2750
..    ...     ...       ...
707  21.0     3.0    7.6500
708  39.0     1.0   31.0000
709  41.0     3.0   14.1083
710  14.0     1.0  120.0000
711  21.0     1.0   77.2875

[712 rows x 3 columns]

In [55]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7430167597765364

In [56]:
# doing the same thing with mean imputation using simple imputation class

si =SimpleImputer()

X_train_trf2= si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [57]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.7374301675977654