In [106]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [107]:
df = pd.read_csv("diamonds.csv")
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  str
 3   color       53940 non-null  str
 4   clarity     53940 non-null  str
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), str(3)
memory usage: 4.5 MB

In [109]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [110]:
df['cut'].unique()

<StringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

In [111]:
df['color'].unique()

<StringArray>
['E', 'I', 'J', 'H', 'F', 'G', 'D']
Length: 7, dtype: str

In [112]:
df['clarity'].unique()

<StringArray>
['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Length: 8, dtype: str

In [113]:
from sklearn.preprocessing import OrdinalEncoder

In [114]:
# categories contain the priority wise format of the values into the columns we want to encode 
ord = OrdinalEncoder(categories=[['Fair','Good','Very Good','Premium','Ideal'],['D','E','F','G','H','I','J'],['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']])

In [115]:
# here we define the column where the encoding will be applied after calculating the value in the categories in the upper cell
ord.fit_transform(df[['cut','color','clarity']])

array([[4., 1., 1.],
       [3., 1., 2.],
       [1., 1., 4.],
       ...,
       [2., 0., 2.],
       [3., 4., 1.],
       [4., 0., 1.]], shape=(53940, 3))

In [116]:
# then changed the values in the main df with the encoded values 
df[['cut','color','clarity']] = ord.fit_transform(df[['cut','color','clarity']])

In [117]:
df.head()

   carat  cut  color  clarity  depth  table  price     x     y     z
0   0.23  4.0    1.0      1.0   61.5   55.0    326  3.95  3.98  2.43
1   0.21  3.0    1.0      2.0   59.8   61.0    326  3.89  3.84  2.31
2   0.23  1.0    1.0      4.0   56.9   65.0    327  4.05  4.07  2.31
3   0.29  3.0    5.0      3.0   62.4   58.0    334  4.20  4.23  2.63
4   0.31  1.0    6.0      1.0   63.3   58.0    335  4.34  4.35  2.75

In [118]:
# now the encoding is done we will do feature scaling

In [119]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [120]:
mn = MinMaxScaler()
mn.fit_transform(df.iloc[:,1:]).shape

(53940, 9)

In [122]:
scale_cols = ["carat", "cut", "color", "clarity", "depth", "table", "x", "y", "z"]
df[scale_cols] = mn.fit_transform(df[scale_cols])

In [123]:
df

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.006237,1.00,0.166667,0.142857,0.513889,0.230769,326,0.367784,0.067572,0.076415
1,0.002079,0.75,0.166667,0.285714,0.466667,0.346154,326,0.362197,0.065195,0.072642
2,0.006237,0.25,0.166667,0.571429,0.386111,0.423077,327,0.377095,0.069100,0.072642
3,0.018711,0.75,0.833333,0.428571,0.538889,0.288462,334,0.391061,0.071817,0.082704
4,0.022869,0.25,1.000000,0.142857,0.563889,0.288462,335,0.404097,0.073854,0.086478
...,...,...,...,...,...,...,...,...,...,...
53935,0.108108,1.00,0.000000,0.285714,0.494444,0.269231,2757,0.535382,0.097793,0.110063
53936,0.108108,0.25,0.000000,0.285714,0.558333,0.230769,2757,0.529795,0.097623,0.113522
53937,0.103950,0.50,0.000000,0.285714,0.550000,0.326923,2757,0.527002,0.096435,0.111950
53938,0.137214,0.75,0.666667,0.142857,0.500000,0.288462,2757,0.572626,0.103905,0.117610
53939,0.114345,1.00,0.000000,0.142857,0.533333,0.230769,2757,0.542831,0.099660,0.114465

In [124]:
from sklearn.model_selection import train_test_split

In [126]:
X = df[scale_cols]
Y = df.iloc[:,6]

In [128]:
X_train , X_test , y_train , y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [129]:
from sklearn.neighbors import KNeighborsRegressor

In [130]:
knn = KNeighborsRegressor()

In [131]:
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [132]:
y_pred = knn.predict(X_test)

In [133]:
from sklearn.metrics import r2_score

In [134]:
r2_score(y_test,y_pred)

0.969298738132559